### ISSUE TITLE
Stackoverflow Exception

### ISSUE THREAD

**Issue by VapidWorx** [dfinke/edge-ps#1]
When using the Get-Command(along with others) it can cause a Stackoverflow Exception.

**Comment by dfinke** [comment]
Thanks for the pointing that out.

Here is the example you sent me.

```
exports.getcommand = function(req, res) {
  var ps=edge.func('ps', 'Get-Command -Verb Set');
  ps(ps, function(err, result){
  if(err) throw err;
   res.send(200, result[0]);
 });
```

In the current implementation, you need to add Out-String to the end of the PowerShell you pass.

I am looking into how best to solve this.

```
exports.getcommand = function(req, res) {
  var ps=edge.func('ps', 'Get-Command -Verb Set | Out-String');
  ps(ps, function(err, result){
  if(err) throw err;
   res.send(200, result[0]);
 });
```
